title: "Mwikuyu Christian C"
description: "Personal website and blog"
url: "https://MwikuyuC.github.io"
baseurl: ""

# Author information
author:
  name: "Mwikuyu Christian C"
  email: "christiandumalukhie@gmail.com"
  github: "MwikuyuC"

# Social links
github_username: MwikuyuC

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
header_pages:
  - about.md
  - education.md
  - resources.md
  - projects.md

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

# Multilingual settings
languages:
  - en
  - ru

default_lang: en
exclude_from_localization: ["assets", "screenshots", "javascript", "images", "css"]

parallel_localization: true

# Language navigation
language_switcher: true

# Language names for display
lang_names:
  en: "English"
  ru: "Русский"
